### ISSUE TITLE
no such file or directory: '/Routes-master/Routes/Constants.swift'

### ISSUE THREAD

**Issue by heshamMassoud** [jacks205/Routes#14]
Hello, I am beginner in iOS swift development. Can you please tell me the steps I need to do to use the latest versions of Alamofire and SwiftJSON for this app to successfully build? because I am getting compile errors through all there files and can't build the app.

Thanks a lot.

**Comment by heshamMassoud** [comment]
Alright, I managed to run it but now I am getting this error when I build the project 

````
<unknown>:0: error: no such file or directory: '/Users/heshammassoud/Documents/TUM/Semester 5/Master Thesis/Routes-master/Routes/Constants.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
````

I also noticed that you have this `Constants.swift` in the .ignore file. Any ideas?

**Comment by jacks205** [comment]
Sorry this project gave you such a headache. This was my first project learning Swift also, so practices and code in this project might not be the best. Also, it's not fully complete since I stopped about midway through.

I see you were able to get the pods installed correctly, but I didn't give exact version numbers in the Podfile, so you're probably using a later version of Alamofire and SwiftyJSON than what I was working with when I was working on Routes, which might be fine.

[Constants.swift](https://gist.github.com/jacks205/1148f423652d6ec4c087) is just a file I omitted that contains private keys and API endpoints I use. It can be found [here](https://gist.github.com/jacks205/1148f423652d6ec4c087), just add it to your Xcode project and make sure its about of the build target and it should compile. The keys should still be valid, but if not, the [HERE Rest API](https://developer.here.com/) is what I used for routing information. You can just make your own account and dig into the API if my keys are no longer valid.

**Comment by heshamMassoud** [comment]
Thanks a lot @jacks205. Don't worry, I am not using the project for learning swift. I am writing a similar routing app as well. And liked the UI on your app :grinning:  So wanted to see it from the inside to get more ideas. Thanks again for your answer :wink:
